### ISSUE TITLE
Search Results Including Pull Requests

### ISSUE THREAD

**Issue by jodylecompte** [despo/issuehub.io#111] opened 2018-06-19 22:04 UTC
I have stumbled upon a few instances where pull requests have slipped into the search results. 

Here is one such example for the label "bug" and search query "php"
![image](https://user-images.githubusercontent.com/38302762/41626670-a496e38c-73e2-11e8-8af8-da7d2c9a612b.png)

Which leads to PR here: https://github.com/mybb/mybb/pull/3266

**Comment by xanderyzwich** [comment] 2018-12-03 13:41
This is due to how issues and pull requests are handled. They are all in the same bucket and there doesn't appear to be any way to distinguish between them when searching.

**Comment by xanderyzwich** [comment] 2018-12-03 13:45
this is a duplicate of #89

**Closed** 2018-12-20 01:58 UTC
