### ISSUE TITLE
Label Suggestion : 'good first bug', 'low hanging fruit', 'First Timer only'

### ISSUE THREAD

**Issue by hoatran1403** [despo/issuehub.io#86] opened 2017-02-06 09:21 UTC
I think it's necessary to have 3 more Labels : 'good first bug', 'low hanging fruit', 'First Timer only'. These labels are important for new contributors

**Comment by xanderyzwich** [comment] 2018-11-02 17:11
duplicate of other issues.  Please close.

**Comment by despo** [comment] 2018-12-19 15:50
Closing as it has been addressed by #143

**Closed by despo** 2018-12-19 15:50 UTC
